### ISSUE TITLE
App is not working on Xubuntu 14.04.2 LTS

### ISSUE THREAD

**Issue by bobmeliev** [mivoligo/Zeegaree#1]
Application is not working on Xubuntu 14.04.2 LTS.

$ python --version
Python 2.7.6

$ python zeegaree.py 
Traceback (most recent call last):
  File "zeegaree.py", line 4, in <module>
    from gi.repository import Unity, Notify
ImportError: cannot import name Unity

**Comment by mivoligo** [comment]
Hi @bobmeliev 
Can you please check if you have all mentioned dependencies installed? https://github.com/mivoligo/Zeegaree#dependencies
